export const drawerItemsMain = [
    {
      key: 'Home',
      title: 'Главная',
      icon: 'home',
      routes: [{nav: 'MainDrawer', routeName: 'Home', subCategory: 'Главная'}],
    },
    {
      key: 'Jewelr',
      title: 'Ювелирные украшения',
      icon: 'diamond',
      routes: [
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Ювелирные украшения', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Кольца', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Серьги', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Гарнитуры', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Подвески', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Броши, булавки, зажимы, запонки', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Колье', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Цепи', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Браслеты', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Бижутерия', category: 'Ювелирные украшения'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Каст', category: 'Ювелирные украшения'},
      ],
    },
    {
      key: 'News',
      title: 'Новости',
      icon: 'newspaper-o',
      routes: [{nav: 'MainDrawer', routeName: 'HelpfulInfo', subCategory: 'Новости'}],
    },
    {
      key: 'Decoration',
      title: 'Предметы интерьера',
      icon: 'cube',
      routes: [
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Предметы интерьера', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Вазы', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Зеркала', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Картины', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Набор для обуви', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Настольные игры', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Плакетки, банкноты', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Посуда', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Светильники, лампы', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Статуэтки, скульптуры', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Часы', category: 'Предметы интерьера'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Шкатулки', category: 'Предметы интерьера'}
      ],
    },
    {
      key: 'Presents',
      title: 'Подарки',
      icon: 'gift',
      routes: [
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Подарки', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'S.T. Dupont', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Ручки', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Сувенирное оружие', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Универсальные подарки', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Религиозные подарки', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Подарки для женщин', category: 'Подарки'},
        {nav: 'MainDrawer', routeName: 'Products', subCategory: 'Подарки для мужчин', category: 'Подарки'},
      ],
    },
    {
      key: 'Watch',
      title: 'Часы',
      icon: 'watch',
      subCategory: 'Часы',
      category: 'Часы',
      routes: [{nav: 'MainDrawer', routeName: 'Products', subCategory: 'Часы',category: 'Часы'}],
    },
    {
      key: 'Silverware',
      title: 'Столовое серебро',
      icon: 'spoon',
      subCategory: 'Столовое серебро',
      category: 'Столовое серебро',
      routes: [{nav: 'MainDrawer', routeName: 'Products', subCategory: 'Столовое серебро', category: 'Столовое серебро'}],
    },
    {
      key: 'CartProd',
      title: 'Корзина',
      icon: 'shopping-cart',
      subCategory: 'Корзина',
      category: 'Корзина',
      routes: [{nav: 'MainDrawer', routeName: 'CartProd', subCategory: 'Корзина', category: 'Корзина'}],
    },
    {
      key: 'About',
      title: 'Справка',
      icon: 'wpforms',
      routes: [
        {nav: 'MainDrawer', routeName: 'About', subCategory: 'О компании'},
        {nav: 'MainDrawer', routeName: 'Services', subCategory: 'Услуги'},
        {nav: 'MainDrawer', routeName: 'Contacts', subCategory: 'Контакты'},
        {nav: 'MainDrawer', routeName: 'PayAndDelivery', subCategory: 'Оплата и доставка'}
      ],
    },
  ];